# -*- coding: utf-8 -*-
"""ruspa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ow48yECyCjy73eXC2ppSBvjK63qbywuH
"""

import streamlit as st

# Configurazione pagina
st.set_page_config(page_title="Verifica Nome", page_icon="🕵️‍♂️")

st.title("Verifica il tuo profilo")

# Input dell'utente
nome_input = st.text_input("Inserisci il tuo nome:")

# Lista dei nomi "speciali" (tutti in minuscolo per il confronto)
nomi_target = ["pierluigi", "pierluigi de rubeis", "ruspa"]

if nome_input:
    # Pulizia dell'input: togliamo spazi extra e rendiamo tutto minuscolo
    nome_pulito = nome_input.strip().lower()

    if nome_pulito in nomi_target:
        st.subheader(f"Sei un gay, {nome_input}!")
        # Assicurati di avere un'immagine chiamata 'pagliaccio.jpg' nella stessa cartella
        # Oppure usa un URL di un'immagine online
        st.image("https://img.freepik.com/premium-photo/clown-holding-broom-sweeping-floor_1025554-154944.jpg",
                 caption="Il pagliaccio con la ramazza", width=400)
    else:
        st.subheader(f"Sei un grande, {nome_input}!")
        # Immagine di una coppa (trofeo)
        st.image("https://img.freepik.com/free-vector/golden-trophy-cup_1284-4733.jpg",
                 caption="Il campione!", width=400)